[package]
name = "yarls"
version = "0.1.0"
authors = ["Baz <github(a)luxolus.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.13"
scraper = "0.9.2"
nom = "4.2.3"
clap = "2.32.0"
selectors = "0.20.0"
strum = "0.15.0"
strum_macros = "0.15.0"
